### ISSUE TITLE
Inventory item duplication when kicked/banned

### ISSUE THREAD

**Issue by EditChris** [zrdzn/GreatLifeSteal#106]
When you use the custom actions feature to ban a player after dying with 1 heart, everything happens so fast that the items on your inventory drops, but stay on the inventory after being revived with a pardon / unban, effectively duplicating them.

It can be _fixed_ adding a "- clear {victim}" command on the parameters, but it would be appreciated that this is fixed the right way.

**Comment by zrdzn** [comment]
Since we can't effectively detect if a custom command is meant to kick/ban someone because there may be many different aliases for the same command and it's bad practice to make a hardcoded check.

1. We could add a boolean property to an each action whether on its activation it should clear victim's drops, e.g.:
```YML
        eliminate:
            enabled: true
            type: DISPATCH_COMMANDS
            clearInventory: true
            parameters: 
            - tempban {victim} 7d
```
In my opinion it's the worst possible solution that can be made because custom actions are not created for ban purposes only, if you have few actions, some of them have this property set to true, some of them to false - what should we do then? It doesn't look nice either.

2. We have an action called BAN in our to-do list and it will have this duplicate 'bug' fixed internally.

3. It may be possible that it's just caused by insta-execute without any delays. We are able to add a fixed amount of ticks that it should wait before executing an action or just add delay as a property to an each action, e.g.:
```YML
        eliminate:
            enabled: true
            type: DISPATCH_COMMANDS
            delay: 5
            parameters: 
            - tempban {victim} 7d
```
If this property would solve this issue, I'd rather add that. I'll test that soon and let you know about my decision.
