### ISSUE TITLE
Add a list of causes - sources that will affect lifesteal system

### ISSUE THREAD

**Issue by zrdzn** [zrdzn/GreatLifeSteal#108]
Instead of the killByPlayerOnly property, there could be a list of boolean causes, e.g.:
```YML
causes:
  players: true
  monsters: true
  fallDamage: false
  burn: false
```
