### ISSUE TITLE
Add per-world support for lifesteal system

### ISSUE THREAD

**Issue by zrdzn** [zrdzn/GreatLifeSteal#139]

**Comment by EditChris** [comment]
Adding this would be amazing, in my case this feature alone could significantly improve how I have my hardcore worlds configured on my server. But, if this is implemented, when a player loses all of their hearts, will they be banned from accessing the entire server, or just from the worlds that we put on the config file?

**Comment by zrdzn** [comment]
There are 2 options in my opinion. 
1 - `disabledWorlds` property in configuration file with worlds where you don't lose hearts and eliminations don't affect this worlds;
2 - Separated lists for eliminations and health losing system:
```YAML
disabledWorlds:
    healthLose:
    - world1
    - world3
    eliminations:
        - world1
        - world2
```
