### ISSUE TITLE
Separate eliminations and revives to different section than customActions

### ISSUE THREAD

**Issue by zrdzn** [zrdzn/GreatLifeSteal#203]
In my opinion, the changes below are more readable and consistent.

From:
```YML
    actions:
        announce:
            enabled: true
            type: BROADCAST
            activateAtHealth: 4.0
            delay: 5
            parameters: 
            - 'Player {victim} has been eliminated by {killer}.'
            revive:
                enabled: false
                commands: []
        eliminate:
            enabled: true
            type: DISPATCH_COMMANDS
            activateAtHealth: 4.0
            delay: 5
            parameters:
            - ban {victim} -r "Eliminated"
            revive:
                enabled: true
                commands:
                - unban {victim}
```
To:
```YML
    actions:
        announce:
            type: BROADCAST
            activateAtHealth: 4.0
            delay: 5
            parameters: 
            - 'Player {victim} has been eliminated by {killer}.'
    eliminations:
        ban:
            activateAtHealth: 4.0
            delay: 5
            commands: 
            - ban {victim} -r "Eliminated"
    revives:
        ban:
          commands:
            initial:
            - unban {victim}
            after:
            - tell {victim} You have been revived!
```
