### ISSUE TITLE
Separate healthChange into victim and killer

### ISSUE THREAD

**Issue by some0ne3** [zrdzn/GreatLifeSteal#83]
Structure could look like this
```yml
    # Amount of health points revoked when a player was killed or awarded when a kill was scored. Can be zero.
    healthChange: 
        victim: 2
        killer: 2
```
